// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	DeleteBook(ctx context.Context, id uuid.UUID) error
	GetAllBooks(ctx context.Context) ([]Book, error)
	GetBook(ctx context.Context, id uuid.UUID) (Book, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
}

var _ Querier = (*Queries)(nil)
